name: Reusable workflow

on:
  workflow_call:
    secrets:
      SECRET_ONE:
        required: false
      GITHUB_TOKEN_OVERRIDE:
        required: false

jobs:
  test-job-reusable:
    runs-on: ubuntu-latest

    steps:
      - name: Print custom repository variables
        run: |
          echo "=== Custom repository variables ==="
          echo "VARIABLE_ONE: ${{ vars.VARIABLE_ONE }}"
          echo ""
          echo "Available vars context (JSON):"
          echo "${{ toJSON(vars) }}"
          echo ""
    
